### ISSUE TITLE
"TemplateDoesNotExist at /rango/"

### ISSUE THREAD

**Issue by polyzy** [taizilongxu/Tango_with_Django_zh_cn#1]
您好，我按照教程做，但在第５部分模板文件这里总是报错。
这是我的settings.py

```
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
TEMPLATES_DIRS = (os.path.join(BASE_DIR, 'templates'),)
```

模板路径的设置我先后用了文中提到的方法和上面这个方法，没有问题。路径是保证没有问题的。
views.py，跟教程中一样。

```
return render(request, 'rango/index.html', context_dict)
```

index.html在`/templates/rango/index.html`
之前写过一个简单的blog，settings.py和views.py跟这个基本差不多，但是没出现过这个问题。不知为何？
查阅了各种资料，总是报找不到模板的错误。

```
Exception Type:     TemplateDoesNotExist
Exception Value:    rango/index.html
```

实在不是问题处在何处？求指点。

**Comment by taizilongxu** [comment]
rango/index.html 换成 index.html 试试呢

**Comment by taizilongxu** [comment]
路由设置的对吗

```
urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls')), # ADD THIS NEW TUPLE!
)
```

再试试 把rango/index.html 改成 index.html呢， 仔细检查下，应当是哪里忽略了吧

**Comment by polyzy** [comment]
血泪教训！原因是拼写错误！
settings.py文件里设置的模板路径是  `TEMPLATE_DIRS`！
不是  `TEMPLATES_DIRS`，也不是  `TEMPLATE_DIR`！

**Comment by taizilongxu** [comment]
哈哈，必经之路啊
