### ISSUE TITLE
4.7.1 hint中返回主页的链接显示有误

### ISSUE THREAD

**Issue by manfeyn** [taizilongxu/Tango_with_Django_zh_cn#3]
> 返回主页的链接是`<a href=".//rango/">Index</a>`.这个结构和上面的about页面里的一样.

中的链接应为 `<a href="/rango/">Index</a>`.

但我查看github上的文件又没有问题，不知是否github与网页没有对应？

**Comment by taizilongxu** [comment]
hi, 刚看了下是mkdocs生成的时候进行了转义,  我看看有啥办法吗

**Comment by taizilongxu** [comment]
OK 升级了下mkdocs解决了

**Comment by manfeyn** [comment]
Great.
